name: cineverse_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons:
  localization: 
  dio: 
  flutter_modular: 
  #flutter_triple: ^2.0.0
  flutter_triple: 
  flutter_svg_provider: 
  onboarding: 
  mobx: 
  mask_text_input_formatter: 
  flutter_mobx: 
  flutter_svg: 
  font_awesome_flutter: 
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/
